name: expression
description: Parser and utilities for Dart expressions.
version: 1.0.0-dev.0

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies: 
  analyzer: ^1.5.0

dev_dependencies:
  lints: ^1.0.0
