name: piko
description: Dart web framework.
version: 1.0.0-dev.32
homepage: https://piko.ykmnkmi.dev

environment:
  sdk: '>=2.13.0-0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.0.2
  build_web_compilers: ^3.0.0
  pedantic: ^1.11.0
  stack_trace: ^1.10.0
