name: piko
description: svelte like dart framework.
version: 1.0.0-dev.7
#homepage: https://www.example.com

environment:
  sdk: '>=2.10.5 <3.0.0'

dependencies: 
  string_scanner: ^1.1.0 

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  pedantic: any
