name: piko
description: Dart web framework.
version: 1.0.0-dev.18
#homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  meta: ^1.3.0
  string_scanner: ^1.1.0 

dev_dependencies:
  # build_runner: any
  # build_web_compilers: any
  pedantic: ^1.10.0
  stack_trace: ^1.10.0
