name: piko
description: svelte like dart framework.
version: 1.0.0-dev.2
#homepage: https://www.example.com

environment:
  sdk: '>=2.10.4 <3.0.0'

dependencies: 

dev_dependencies:
  angular_ast: ^1.0.1
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
