name: piko
description: Dart web framework.
version: 1.0.0-dev.20
homepage: https://piko.ykmnkmi.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  meta: ^1.3.0
  string_scanner: ^1.1.0 

dev_dependencies:
  build_runner: ^1.12.0
  build_web_compilers: ^2.16.0
  pedantic: ^1.0.0
  stack_trace: ^1.0.0
