name: ast
description: Angular AST library fork.
version: 1.0.0-dev.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies: 
  meta: ^1.3.0
  source_span: ^1.8.1
  string_scanner: ^1.1.0

dev_dependencies:
  lints: ^1.0.1
