name: piko
description: An absolute bare-bones web app.
version: 1.0.0-dev.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  angular_ast: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.4
  build_web_compilers: ^3.0.0
  lints: ^1.0.1
  path: ^1.8.0
  stack_trace: ^1.10.0
  stream_transform: ^2.0.0

dependency_overrides:
  angular_ast:
    git:
      path: angular_ast
      ref: google
      url: https://github.com/angulardart/angular
